/**
 * The type half of the export-parity test (AC 1, AC 9, scenario EXP-1; D6, D10).
 *
 * Each `import type` below reads every type name that the matching upstream entry point of
 * xstate@5.33.2 exports (the frozen manifest, `exports.<entry>.types`) from the port entry
 * point that mirrors it. The test type-check (`tsconfig.test.json`; `tsconfig.test.green.json`
 * once the file is not pending) resolves each name, so a missing type fails it. A type name
 * that the port does not export on purpose is left out here and named by a deviation row of
 * the ledger; `exports.test.ts` checks that every upstream type name is imported here or
 * ledgered. Names of the subpath entry points carry the entry as a prefix (`Actions_...`),
 * because several entry points export the same name.
 *
 * The last three imports read the names that D6 leaves unported. Each sits under its own
 * `@ts-expect-error` line: when the root exports the name as a type or a value, the directive
 * is unused (TS2578) and the test type-check fails (AC 9).
 */

// . (upstream src/index.ts): 209 of its 211 type names (InteropObservable: ledger DEV-57; Subscription: below)
import type {
  Action,
  ActionArgs,
  ActionExecutor,
  ActionFunction,
  ActionFunctionMap,
  Actions,
  ActorLike,
  ActorLogic,
  ActorLogicFrom,
  ActorOptions,
  ActorRef,
  ActorRefFrom,
  ActorRefFromLogic,
  ActorRefLike,
  ActorScope,
  ActorSystem,
  ActorSystemInfo,
  AnyActor,
  AnyActorLogic,
  AnyActorRef,
  AnyActorScope,
  AnyEventObject,
  AnyFunction,
  AnyHistoryValue,
  AnyInterpreter,
  AnyInvokeConfig,
  AnyMachineSnapshot,
  AnyState,
  AnyStateConfig,
  AnyStateMachine,
  AnyStateNode,
  AnyStateNodeConfig,
  AnyStateNodeDefinition,
  AnyTransitionConfig,
  AnyTransitionDefinition,
  AssignAction,
  AssignArgs,
  Assigner,
  AtomicStateNodeConfig,
  BaseActorRef,
  BuiltinActionResolution,
  CallbackActorLogic,
  CallbackActorRef,
  CallbackLogicFunction,
  CallbackSnapshot,
  CancelAction,
  Cast,
  Compute,
  ConditionalRequired,
  ContextFactory,
  ContextFrom,
  DelayConfig,
  DelayExpr,
  DelayFunctionMap,
  DelayedTransitionDefinition,
  DelayedTransitions,
  DevToolsAdapter,
  DoNotInfer,
  DoneActorEvent,
  DoneStateEvent,
  Elements,
  EmitAction,
  EmittedFrom,
  EnqueueActionsAction,
  Equals,
  ErrorActorEvent,
  EventDescriptor,
  EventFrom,
  EventFromLogic,
  EventObject,
  ExecutableActionObject,
  ExecutableActionsFrom,
  ExecutableSpawnAction,
  ExtractEvent,
  GetConcreteByKey,
  GetParameterizedParams,
  GuardArgs,
  GuardPredicate,
  HistoryStateNode,
  HistoryStateNodeConfig,
  HistoryValue,
  HomomorphicOmit,
  HomomorphicPick,
  Identity,
  IndexByProp,
  IndexByType,
  InferEvent,
  InitialTransitionConfig,
  InitialTransitionDefinition,
  InputFrom,
  InspectedActionEvent,
  InspectedActorEvent,
  InspectedEventEvent,
  InspectedMicrostepEvent,
  InspectedSnapshotEvent,
  InspectedTransitionEvent,
  InspectionEvent,
  InternalMachineImplementations,
  InteropSubscribable,
  Interpreter,
  InterpreterFrom,
  Invert,
  InvokeConfig,
  InvokeDefinition,
  IsAny,
  IsLiteralString,
  IsNever,
  IsNotNever,
  Lazy,
  LogAction,
  LogExpr,
  LowInfer,
  MachineConfig,
  MachineContext,
  MachineImplementationsFrom,
  MachineImplementationsSimplified,
  MachineOptions,
  MachineSnapshot,
  MachineTypes,
  Mapper,
  MaybeLazy,
  Merge,
  MetaObject,
  NoInfer,
  NoRequiredParams,
  NonReducibleUnknown,
  ObservableActorLogic,
  ObservableActorRef,
  ObservableSnapshot,
  Observer,
  OutputFrom,
  ParameterizedObject,
  PartialAssigner,
  PersistedHistoryValue,
  PromiseActorLogic,
  PromiseActorRef,
  PromiseSnapshot,
  Prop,
  PropertyAssigner,
  ProvidedActor,
  RaiseAction,
  RaiseActionOptions,
  RaiseActionParams,
  Readable,
  RequiredActorOptions,
  RequiredActorOptionsKeys,
  RequiredLogicInput,
  ResolvedStateMachineTypes,
  RoutableStateId,
  RouteTransitionConfig,
  SendExpr,
  SendToAction,
  SendToActionOptions,
  SendToActionParams,
  SetupReturn,
  SetupTypes,
  SimpleOrStateNodeConfig,
  SingleOrArray,
  Snapshot,
  SnapshotEvent,
  SnapshotFrom,
  SnapshotStatus,
  SpawnAction,
  SpawnActionOptions,
  Spawner,
  SpecialExecutableAction,
  StateConfig,
  StateFrom,
  StateId,
  StateKey,
  StateLike,
  StateMachineDefinition,
  StateMachineTypes,
  StateNodeConfig,
  StateNodeDefinition,
  StateNodesConfig,
  StateSchema,
  StateSchemaFrom,
  StateTypes,
  StateValue,
  StateValueFrom,
  StateValueMap,
  StatesConfig,
  StatesDefinition,
  StopAction,
  Subscribable,
  TODO,
  TagsFrom,
  ToChildren,
  ToExecutableAction,
  ToStateValue,
  TransitionActorLogic,
  TransitionActorRef,
  TransitionConfig,
  TransitionConfigOrTarget,
  TransitionConfigTarget,
  TransitionDefinition,
  TransitionDefinitionMap,
  TransitionSnapshot,
  TransitionTarget,
  Transitions,
  TransitionsConfig,
  UnifiedArg,
  UnknownAction,
  UnknownActorLogic,
  UnknownActorRef,
  UnknownMachineConfig,
  Values,
  WithDynamicParams
} from "../../src/index.js"

// ./actions (upstream src/actions.ts): 11 type names
import type {
  AssignAction as Actions_AssignAction,
  AssignArgs as Actions_AssignArgs,
  CancelAction as Actions_CancelAction,
  EmitAction as Actions_EmitAction,
  EnqueueActionsAction as Actions_EnqueueActionsAction,
  LogAction as Actions_LogAction,
  RaiseAction as Actions_RaiseAction,
  SendToAction as Actions_SendToAction,
  SpawnAction as Actions_SpawnAction,
  SpawnActionOptions as Actions_SpawnActionOptions,
  StopAction as Actions_StopAction
} from "../../src/actions/index.js"

// ./actors (upstream src/actors/index.ts): 13 type names
import type {
  CallbackActorLogic as Actors_CallbackActorLogic,
  CallbackActorRef as Actors_CallbackActorRef,
  CallbackLogicFunction as Actors_CallbackLogicFunction,
  CallbackSnapshot as Actors_CallbackSnapshot,
  ObservableActorLogic as Actors_ObservableActorLogic,
  ObservableActorRef as Actors_ObservableActorRef,
  ObservableSnapshot as Actors_ObservableSnapshot,
  PromiseActorLogic as Actors_PromiseActorLogic,
  PromiseActorRef as Actors_PromiseActorRef,
  PromiseSnapshot as Actors_PromiseSnapshot,
  TransitionActorLogic as Actors_TransitionActorLogic,
  TransitionActorRef as Actors_TransitionActorRef,
  TransitionSnapshot as Actors_TransitionSnapshot
} from "../../src/actors/index.js"

// ./dev (upstream src/dev/index.ts): 1 type name
import type {
  XStateDevInterface as Dev_XStateDevInterface
} from "../../src/dev/index.js"

// ./graph (upstream src/graph/index.ts): 23 type names
import type {
  AdjacencyMap as Graph_AdjacencyMap,
  AdjacencyValue as Graph_AdjacencyValue,
  AnyStateNode as Graph_AnyStateNode,
  DirectedGraphEdge as Graph_DirectedGraphEdge,
  DirectedGraphNode as Graph_DirectedGraphNode,
  EventExecutor as Graph_EventExecutor,
  PathGenerator as Graph_PathGenerator,
  SerializationConfig as Graph_SerializationConfig,
  SerializedEvent as Graph_SerializedEvent,
  SerializedSnapshot as Graph_SerializedSnapshot,
  StatePath as Graph_StatePath,
  StatePlanMap as Graph_StatePlanMap,
  Step as Graph_Step,
  Steps as Graph_Steps,
  TestMeta as Graph_TestMeta,
  TestModelOptions as Graph_TestModelOptions,
  TestParam as Graph_TestParam,
  TestPath as Graph_TestPath,
  TestPathResult as Graph_TestPathResult,
  TestStepResult as Graph_TestStepResult,
  TraversalConfig as Graph_TraversalConfig,
  TraversalOptions as Graph_TraversalOptions,
  VisitedContext as Graph_VisitedContext
} from "../../src/graph/index.js"

// ./guards (upstream src/guards.ts): 4 type names
import type {
  Guard as Guards_Guard,
  GuardArgs as Guards_GuardArgs,
  GuardPredicate as Guards_GuardPredicate,
  UnknownGuard as Guards_UnknownGuard
} from "../../src/guards/index.js"

// D6: interpret, toObserver and Subscription are not ported (ledger DEV-1, DEV-2, DEV-4)
// @ts-expect-error interpret is not ported (D6): the root exports no interpret
import type { interpret } from "../../src/index.js"
// @ts-expect-error toObserver is not ported (D6): the root exports no toObserver
import type { toObserver } from "../../src/index.js"
// @ts-expect-error Subscription is not ported (D6): a subscription ends with its Scope
import type { Subscription } from "../../src/index.js"
